
-- Create FM_MENU 
CREATE TABLE FM_MENU
(
   MENUID              NUMBER NOT NULL,
   MENUNAME            VARCHAR2 (40),
   ISROOT              VARCHAR2 (1),
   POSITION            NUMBER,
   MENUTYPE            VARCHAR2 (40),
   PARENTMENUID        NUMBER,
   FM_METADATA         VARCHAR2 (40),
   FM_POLICYMETADATA   VARCHAR2 (40),
   ADMINFLAG           VARCHAR2 (1)
);

ALTER TABLE FM_MENU ADD CONSTRAINT PK_FM_MENU PRIMARY KEY(MENUID);


-- Create FM_METADATA

CREATE TABLE FM_METADATA
(
   TABLENAME     VARCHAR2 (40),
   COLUMNNAME    VARCHAR2 (40),
   ISKEY         VARCHAR2 (1),
   DATATYPE      VARCHAR2 (40),
   ISREQUIRED    VARCHAR2 (1),
   INPUTTYPE     VARCHAR2 (40),
   SELECTQUERY   VARCHAR2 (2000)
);

ALTER TABLE FM_METADATA ADD CONSTRAINT PK_FM_METADATA PRIMARY KEY(TABLENAME,COLUMNNAME);