
-- Create FM_MENU 
CREATE TABLE FM_MENU
(
   MENUID              NUMBER NOT NULL,
   MENUNAME            VARCHAR2 (40),
   ISROOT              VARCHAR2 (1),
   POSITION            NUMBER,
   MENUTYPE            VARCHAR2 (40),
   PARENTMENUID        NUMBER,
   FM_MENUDATA         VARCHAR2 (40),
   FM_POLICYMETADATA   VARCHAR2 (40),
   ADMINFLAG           VARCHAR2 (1)
);

CREATE UNIQUE INDEX PK_FM_MENU
   ON FM_MENU (MENUID);